// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3uqvg2llLJBhz5PMqZ4O23_HTaFnwIqQ',
    appId: '1:554477332287:web:47d04e50049405d2d7158a',
    messagingSenderId: '554477332287',
    projectId: 'chat-app-1167a',
    authDomain: 'chat-app-1167a.firebaseapp.com',
    storageBucket: 'chat-app-1167a.appspot.com',
    measurementId: 'G-XNLRLGX67D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0k5XJCYSw_6Db485xgjVUcNlmLiauj3s',
    appId: '1:554477332287:android:d0745b6e400c0d47d7158a',
    messagingSenderId: '554477332287',
    projectId: 'chat-app-1167a',
    storageBucket: 'chat-app-1167a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA12D1A0xAy9MrnyJMPNR2Fy4jJH6TLYkw',
    appId: '1:554477332287:ios:8c4f5caae64d2863d7158a',
    messagingSenderId: '554477332287',
    projectId: 'chat-app-1167a',
    storageBucket: 'chat-app-1167a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA12D1A0xAy9MrnyJMPNR2Fy4jJH6TLYkw',
    appId: '1:554477332287:ios:8c4f5caae64d2863d7158a',
    messagingSenderId: '554477332287',
    projectId: 'chat-app-1167a',
    storageBucket: 'chat-app-1167a.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3uqvg2llLJBhz5PMqZ4O23_HTaFnwIqQ',
    appId: '1:554477332287:web:f0f742c7bbe13dc3d7158a',
    messagingSenderId: '554477332287',
    projectId: 'chat-app-1167a',
    authDomain: 'chat-app-1167a.firebaseapp.com',
    storageBucket: 'chat-app-1167a.appspot.com',
    measurementId: 'G-87EYLZSPTE',
  );
}
